#ifndef TPM_H_
#define TPM_H_
#include "tss2_tpm2_types.h"
#include "ui.h"
#include <tss2/tss2_esys.h>
#include <tss2/tss2_rc.h>
#include <tss2/tss2_tctildr.h>

/**
 * The TCTI or "Transmission Interface" is the communication mechanism with the
 * TPM.
 *
 * This structure manages the TCTI context and ensures it is properly
 * finalized upon destruction.
 *
 * https://github.com/tpm2-software/tpm2-tools/blob/master/man/common/tcti.md
 */
struct TctiCtx {
  TSS2_TCTI_CONTEXT *ctx = nullptr; ///< Pointer to the TCTI context
  ~TctiCtx() {
    if (ctx) {
      Tss2_TctiLdr_Finalize(&ctx);
      ok("TCTI Deinitialized");
    }
  }
};

/**
 * ESYS Context
 *
 * This structure manages the ESYS context and ensures it is properly
 * finalized upon destruction.
 *
 * https://tpm2-tss.readthedocs.io/en/latest/group___e_s_y_s___c_o_n_t_e_x_t.html
 */
struct EsysCtx {
  ESYS_CONTEXT *ctx = nullptr; ///< Pointer to the ESYS context
  ~EsysCtx() {
    if (ctx) {
      Esys_Finalize(&ctx);
      ok("ESYS Deinitialized");
    }
  }
};

/**
 * Checks the TPM2 return code and reports if an error occurred.
 *
 * @param rc The return code to check.
 * @param what Contextual information about where the error occurred.
 * @return True if the return code indicates success, false otherwise.
 */
static bool CheckRC(TSS2_RC rc, const char *what) {
  if (rc != TSS2_RC_SUCCESS) {
    const char *decoded = Tss2_RC_Decode(rc);
    fail(std::string(what) + (decoded ? decoded : "unknown"));
    return false;
  }
  return true;
}

/**
 * Makes RSA Storage Primary Template
 *
 * This function creates a template for a storage primary RSA key with specific
 * attributes and parameters suitable for secure storage operations.
 *
 * @return A TPM2B_PUBLIC structure representing the RSA storage primary
 * template.
 */
static TPM2B_PUBLIC MakeRSAStoragePrimaryTemplate() {
  // Create a template for a storage primary RSA key
  TPM2B_PUBLIC inPublic{};
  inPublic.publicArea.type = TPM2_ALG_RSA;
  inPublic.publicArea.nameAlg = TPM2_ALG_SHA256;

  // Restricted decrypt primary (storage key)
  inPublic.publicArea.objectAttributes =
      TPMA_OBJECT_FIXEDTPM | TPMA_OBJECT_FIXEDPARENT |
      TPMA_OBJECT_SENSITIVEDATAORIGIN | TPMA_OBJECT_USERWITHAUTH |
      TPMA_OBJECT_RESTRICTED | TPMA_OBJECT_DECRYPT;

  inPublic.publicArea.authPolicy.size = 0;

  // Symmetric inner wrapper for restricted decrypt keys
  inPublic.publicArea.parameters.rsaDetail.symmetric.algorithm = TPM2_ALG_AES;
  inPublic.publicArea.parameters.rsaDetail.symmetric.keyBits.aes = 128;
  inPublic.publicArea.parameters.rsaDetail.symmetric.mode.aes = TPM2_ALG_CFB;

  // No signing scheme on a storage key
  inPublic.publicArea.parameters.rsaDetail.scheme.scheme = TPM2_ALG_NULL;

  inPublic.publicArea.parameters.rsaDetail.keyBits = 2048;
  inPublic.publicArea.parameters.rsaDetail.exponent = 0;
  inPublic.publicArea.unique.rsa.size = 0;
  return inPublic;
}

/**
 * Makes RSA Signing Child Template
 *
 * This function creates a template for an RSA signing child key. The resulting
 * TPM2B_PUBLIC structure is configured for a 2048-bit RSA key that:
 *
 * - Uses SHA-256 as its name algorithm
 * - Is bound to the TPM and its parent (FIXEDTPM, FIXEDPARENT)
 * - Has its sensitive data generated by the TPM (SENSITIVEDATAORIGIN)
 * - Requires user authorization for usage (USERWITHAUTH)
 * - Is restricted to signing and encryption operations (SIGN_ENCRYPT)
 * - Has no symmetric algorithm specified (symmetric.algorithm = TPM2_ALG_NULL)
 * - Uses RSASSA with SHA-256 for its signing scheme
 *
 * @return A TPM2B_PUBLIC structure representing the RSA signing child key
 * template.
 */
static TPM2B_PUBLIC MakeRSASigningChildTemplate() {
  TPM2B_PUBLIC c{};
  c.publicArea.type = TPM2_ALG_RSA;
  c.publicArea.nameAlg = TPM2_ALG_SHA256;

  c.publicArea.objectAttributes =
      TPMA_OBJECT_FIXEDTPM | TPMA_OBJECT_FIXEDPARENT |
      TPMA_OBJECT_SENSITIVEDATAORIGIN | TPMA_OBJECT_USERWITHAUTH |
      TPMA_OBJECT_SIGN_ENCRYPT;

  c.publicArea.authPolicy.size = 0;

  c.publicArea.parameters.rsaDetail.symmetric.algorithm = TPM2_ALG_NULL;

  c.publicArea.parameters.rsaDetail.scheme.scheme = TPM2_ALG_RSASSA;
  c.publicArea.parameters.rsaDetail.scheme.details.rsassa.hashAlg =
      TPM2_ALG_SHA256;

  c.publicArea.parameters.rsaDetail.keyBits = 2048;
  c.publicArea.parameters.rsaDetail.exponent = 0;

  c.publicArea.unique.rsa.size = 0;
  return c;
}

/**
 * Connects to the TPM using TCTI and ESYS contexts.
 *
 * @param args The command line arguments.
 * @param tctiConf The TCTI configuration string.
 * @param tcti The TctiCtx structure to initialize.
 * @param esys The EsysCtx structure to initialize.
 * @return True if connection is successful, false otherwise.
 */
bool ConnectTPM(Args &args, std::string tctiConf, TctiCtx &tcti, EsysCtx &esys);

/**
 * Starts an authorization session with the TPM.
 *
 * @param args The command line arguments.
 * @param esys The EsysCtx structure used to communicate with the TPM.
 * @param session_handle Output parameter that receives the ESYS_TR session
 * handle.
 * @returns True if the session is started successfully, false otherwise.
 */
bool TPMStartAuth(Args &args, EsysCtx &esys, ESYS_TR &sessionHandle);

/**
 * Connects to the TPM and performs a startup operation.
 *
 * @param args The command line arguments.
 * @param esys The EsysCtx structure to initialize.
 * @return True if TPM startup is successful, false otherwise.
 */
bool TPMStartup(Args &args, EsysCtx &esys);

/**
 * Creates a primary key in the TPM under the Owner Hierarchy.
 *
 * @param args The command line arguments.
 * @param esys The EsysCtx structure to use for the operation.
 * @param primaryHandle The handle of the created primary key.
 * @return True if key creation is successful, false otherwise.
 */
bool TPMCreatePrimary(Args &args, EsysCtx &esys, ESYS_TR &primaryHandle,
                      ESYS_TR sessionHandle = ESYS_TR_PASSWORD);

/**
 * Creates and loads a child signing key under the specified primary key.
 *
 * This function uses the provided primary key (identified by @p primaryHandle)
 * as the parent to create a child signing key in the TPM, and then loads that
 * key so it can be used for signing operations.
 *
 * The child key parameters (for example, RSA/ECC type, key size, signing
 * scheme, and other object attributes) are derived from the command line
 * arguments contained in @p args. The actual key template is constructed
 * internally (for example, via MakeRSASigningChildTemplate or an equivalent
 * helper).
 *
 * Authorization for both TPM2_Create and TPM2_Load is provided through
 * @p sessionHandle, which can be a password session, an HMAC session, or any
 * other supported authorization session. The primary key must already exist
 * and be loaded in the TPM, and its handle supplied via @p primaryHandle.
 *
 * On success, the function returns a handle to the loaded child key via
 * @p childHandle. The caller is responsible for managing the lifetime of this
 * handle and flushing it from the TPM when it is no longer needed.
 *
 * @param args           Command line arguments describing the child key
 *                       configuration and behavior.
 * @param esys           EsysCtx structure providing the ESAPI context used
 *                       to talk to the TPM.
 * @param primaryHandle  Handle of the already-created and loaded primary key
 *                       under which the child signing key will be created.
 * @param sessionHandle  Authorization session handle used to authorize both
 *                       the creation and loading of the child key.
 * @param childHandle    Output parameter that receives the handle of the
 *                       loaded child signing key on success. Set to
 *                       ESYS_TR_NONE on failure.
 *
 * @return true if the child signing key is successfully created and loaded
 *         into the TPM; false if any error occurs during creation or loading.
 */
bool TPMCreateLoad(Args &args, EsysCtx &esys, ESYS_TR &primaryHandle,
                   ESYS_TR sessionHandle, ESYS_TR &childHandle);
#endif // TPM_H_
